### ISSUE TITLE
Summary prints results with wrong labels

### ISSUE THREAD

**Issue by IreneSchmidtmann** [happma/WMWssp#1]
Dear Martin Happ,

when using summary to display the results of function WMWssp(), the numbers are displayed with the wrong labels. The error seems to be already in the results vector.  I can guess which number means what, but it would be nice if you could correct this. Probably the number 0.8035714 has to be excluded from the vector, then everything moves in place.

Best regards
Irene Schmidtmann

My example code:
------------------------------------
library(WMWssp)
control <- c(1.5, 2.5, 3.0, 2.0, 2.0, 3.0, 3.0, 2.5)
acitretin <- c(2.5, 3.0, 2.5, 3.0, 4.0, 3.5, 3.5)
summary(WMWssp(control, acitretin, alpha = 0.025, power = 0.9, t = 1/2,
               simulation = TRUE, nsim = 10000))
------------------------------------

Output produced:

Simulation:
1000 / 10000 
2000 / 10000 
3000 / 10000 
4000 / 10000 
5000 / 10000 
6000 / 10000 
7000 / 10000 
8000 / 10000 
9000 / 10000 
10000 / 10000 

Wilcoxon-Mann-Whitney Sample Size Calculation
 
Summary
Call: WMWssp
Type-I error (two-sided): 0.025
Power: 0.9

                                Results
alpha (2-sided)               0.0250000
Power                         0.9000000
Simulated Power               0.9458000
N (total sample size needed)  0.8035714
t=n1/N                       33.6454152
n1 in Group 1                 0.5000000
n2 in Group 2                16.8227076
N rounded                    16.8227076
n1 rounded                   34.0000000
n2 rounded                   17.0000000
11                           17.0000000

**Comment by happma** [comment]
Dear Irene Schmidtmann,
Thank you, I have fixed this issue. 
The labels are indeed wrong when "simulation = TRUE" is used.
Best regards,
Martin Happ

                                Results
alpha (2-sided)               0.0250000
Power                         0.9000000
Simulated Power               0.9466000
Estimated relative effect p   0.8035714
N (total sample size needed) 33.6454152
t=n1/N                        0.5000000
n1 in Group 1                16.8227076
n2 in Group 2                16.8227076
N rounded                    34.0000000
n1 rounded                   17.0000000
n2 rounded                   17.0000000

**Comment by IreneSchmidtmann** [comment]
Dear Martin Happ,

Thank you very much for the quick fix. I downloaded the new version and it works as expected.

Best regards
Irene Schmidtmann
